"""
Morocco agricultural crop calendar.
Organised by region (6 agro-climatic zones) and month (1-12).
Data reflects official ONCA / IAV Hassan II extension recommendations.
"""
from datetime import date

# ── City → Region mapping ─────────────────────────────────────────────────────
CITY_REGION = {
    # Sais-Centre (fertile plateau, dominant cereal zone)
    "meknès": "sais", "meknes": "sais", "مكناس": "sais",
    "fès": "sais", "fes": "sais", "فاس": "sais",
    "beni mellal": "sais", "béni mellal": "sais", "بني ملال": "sais",
    "benimellal": "sais", "بنيملال": "sais",
    "khouribga": "sais", "خريبكة": "sais",
    "khemisset": "sais", "khémisset": "sais",
    "errachidia": "sais",
    "tadla": "sais", "تادلة": "sais",
    # Gharb-Atlantique (irrigated plains, diversified crops)
    "casablanca": "gharb", "الدار البيضاء": "gharb", "الدارالبيضاء": "gharb",
    "rabat": "gharb", "الرباط": "gharb",
    "kenitra": "gharb",
    "el jadida": "gharb", "الجديدة": "gharb",
    "settat": "gharb", "سطات": "gharb",
    "safi": "gharb", "آسفي": "gharb",
    "gharb": "gharb", "الغرب": "gharb",
    # Tensift-Haouz (semi-arid, olives, palms, early vegetables)
    "marrakech": "tensift", "marrakesh": "tensift", "مراكش": "tensift",
    "ouarzazate": "tensift", "ورزازات": "tensift",
    # Souss-Massa (arid coast, citrus, early export vegetables)
    "agadir": "souss", "أكادير": "souss",
    "tiznit": "souss",
    "souss": "souss", "سوس": "souss",
    # Nord-Rif (humid Mediterranean)
    "tanger": "nord", "tangier": "nord", "طنجة": "nord",
    "tétouan": "nord", "tetouan": "nord", "تطوان": "nord",
    "larache": "nord",
    "chefchaouen": "nord",
    "nador": "nord", "الناظور": "nord",
    # Oriental (continental semi-arid)
    "oujda": "oriental", "وجدة": "oriental",
    "taza": "oriental",
}

REGION_LABELS = {
    "sais":     {"fr": "Saïs-Centre",      "ar": "سايس - الوسط"},
    "gharb":    {"fr": "Gharb-Atlantique",  "ar": "الغرب الأطلسي"},
    "tensift":  {"fr": "Tensift-Haouz",     "ar": "تانسيفت-الحوز"},
    "souss":    {"fr": "Souss-Massa",       "ar": "سوس ماسة"},
    "nord":     {"fr": "Nord-Rif",          "ar": "الشمال-الريف"},
    "oriental": {"fr": "Oriental",          "ar": "الشرق"},
}

# ── Calendar data ─────────────────────────────────────────────────────────────
# Keys: "plant", "harvest", "tasks", "alert" (optional)
CALENDAR = {

    "sais": {
        1:  {"plant": ["blé tendre", "orge (tardif)", "fèves"],
             "harvest": ["carottes", "choux", "navets"],
             "tasks": ["Surveiller la rouille jaune sur blé", "Irriguer si gel prolongé"],
             "alert": "Risque de gel — protéger les semis précoces"},
        2:  {"plant": ["pois chiches", "lentilles", "oignons (plants)"],
             "harvest": ["choux-fleurs", "épinards"],
             "tasks": ["Apport d'azote sur céréales", "Désherbage blé et orge"]},
        3:  {"plant": ["pommes de terre (primeur)", "tomates (sous-abri)", "maïs"],
             "harvest": ["fèves vertes (précoces)", "carottes"],
             "tasks": ["Traitement fongique céréales", "Préparer sol pour printemps"]},
        4:  {"plant": ["tournesol", "betterave sucrière", "courgettes"],
             "harvest": ["fèves", "pois chiches (précoces)", "oignons verts"],
             "tasks": ["Fertilisation potassique olives", "Irrigation de montée en épi"]},
        5:  {"plant": ["maïs grain", "sorgho", "melons"],
             "harvest": ["pommes de terre primeur", "lentilles", "ail"],
             "tasks": ["Surveillance pucerons sur céréales", "Préparer moissonneuse"]},
        6:  {"plant": ["sorgho fourrager", "maïs ensilage"],
             "harvest": ["blé tendre", "orge", "triticale"],
             "tasks": ["Moisson — stocker au sec", "Traiter les grains contre charançons"],
             "alert": "Saison de moisson — surveiller la météo pour éviter pertes"},
        7:  {"plant": ["maïs (irrigué)", "tournesol tardif"],
             "harvest": ["blé dur", "pois chiches", "oignons secs"],
             "tasks": ["Labour post-moisson", "Chaulage des sols acides"]},
        8:  {"plant": ["navets", "radis", "épinards (semi-précoce)"],
             "harvest": ["maïs ensilage (précoce)", "tournesol"],
             "tasks": ["Préparer terres pour semis d'automne", "Entretien des oliveraies"]},
        9:  {"plant": ["blé dur (très précoce)", "fèves", "luzerne"],
             "harvest": ["maïs grain", "sorgho"],
             "tasks": ["Labour profond", "Analyse de sol avant fertilisation"],
             "alert": "Début de la fenêtre de semis — ne pas semer trop tôt"},
        10: {"plant": ["blé tendre", "blé dur", "orge", "fèves"],
             "harvest": ["olives (début)", "maïs", "betterave sucrière"],
             "tasks": ["Semis en ligne, profondeur 3-5 cm", "Irriguer après semis si sol sec"]},
        11: {"plant": ["blé tendre (tardif)", "féveroles", "pois"],
             "harvest": ["olives", "carottes", "betterave"],
             "tasks": ["Fertilisation de fond P₂O₅-K₂O", "Taille de formation oliviers"]},
        12: {"plant": ["ail", "oignons (bulbes)"],
             "harvest": ["olives (tardif)", "choux", "navets"],
             "tasks": ["Irrigation hivernale légère", "Protéger contre les gelées nocturnes"]},
    },

    "gharb": {
        1:  {"plant": ["betterave sucrière", "blé", "orge"],
             "harvest": ["choux", "carottes", "poireaux"],
             "tasks": ["Contrôle excès d'eau (drainage)", "Surveiller les maladies du pied"]},
        2:  {"plant": ["pois chiches", "oignons", "pommes de terre"],
             "harvest": ["épinards", "choux-fleurs"],
             "tasks": ["Apport azoté fractionné", "Désherbage betterave"]},
        3:  {"plant": ["tomates plein champ", "poivrons", "aubergines"],
             "harvest": ["fèves vertes", "pois mange-tout"],
             "tasks": ["Irrigation goutte-à-goutte à installer", "Taille framboisiers"]},
        4:  {"plant": ["maïs", "soja", "melons", "courgettes"],
             "harvest": ["pommes de terre primeur", "oignons verts"],
             "tasks": ["Traitement insecticides tomates", "Paillage melons"]},
        5:  {"plant": ["pastèques", "concombres", "haricots verts"],
             "harvest": ["tomates (sous-abri)", "fèves sèches"],
             "tasks": ["Irrigation intensive", "Surveiller mouche blanche"],
             "alert": "Début de la chaleur — augmenter fréquence d'irrigation"},
        6:  {"plant": ["sorgho", "tournesol", "maïs tardif"],
             "harvest": ["blé", "orge", "ail", "oignons secs"],
             "tasks": ["Moisson céréales", "Traitement post-récolte greniers"]},
        7:  {"plant": ["maïs irrigué", "haricots"],
             "harvest": ["pastèques", "melons", "tomates"],
             "tasks": ["Labour estival", "Entretien système d'irrigation"]},
        8:  {"plant": ["navets", "carottes", "radis", "betterave potagère"],
             "harvest": ["maïs", "tournesol", "concombres"],
             "tasks": ["Préparer planches légumes automne", "Analyse pH sol"]},
        9:  {"plant": ["blé (essai précoce)", "betterave sucrière", "luzerne"],
             "harvest": ["maïs grain", "sorgho", "haricots secs"],
             "tasks": ["Labour et préparation lit de semences"]},
        10: {"plant": ["blé tendre", "blé dur", "orge", "fèves"],
             "harvest": ["betterave sucrière", "maïs", "olives"],
             "tasks": ["Semis céréales d'automne", "Irriguer juste après semis"]},
        11: {"plant": ["féveroles", "pois", "oignons"],
             "harvest": ["olives", "carottes", "choux"],
             "tasks": ["Fertilisation minérale de fond", "Entretien canaux drainage"]},
        12: {"plant": ["ail", "épinards", "blé tardif"],
             "harvest": ["olives (fin)", "choux", "poireaux"],
             "tasks": ["Contrôle humidité sol", "Protéger plants sensibles au gel"]},
    },

    "tensift": {
        1:  {"plant": ["fèves", "pois chiches", "oignons"],
             "harvest": ["olives (fin)", "choux", "carottes"],
             "tasks": ["Taille oliviers après récolte", "Pailler les agrumes"],
             "alert": "Nuits froides possibles — protéger citrus et plantules"},
        2:  {"plant": ["pommes de terre", "tomates (sous-abri)", "poivrons"],
             "harvest": ["oranges (tardives)", "mandarines"],
             "tasks": ["Fertilisation azotée oliviers", "Travail du sol avant printemps"]},
        3:  {"plant": ["maïs", "courgettes", "melons (précoces)"],
             "harvest": ["fèves vertes", "pois chiches"],
             "tasks": ["Irrigation intensive (chaleur précoce)", "Taille palmiers dattiers"]},
        4:  {"plant": ["pastèques", "melons", "piments"],
             "harvest": ["oranges", "pommes de terre primeur"],
             "tasks": ["Paillage cultures maraîchères", "Surveiller hygrométrie"],
             "alert": "Vents chauds (chergui) — risque de brûlure foliaire"},
        5:  {"plant": ["sorgho (irrigué)", "haricots verts"],
             "harvest": ["melons précoces", "tomates"],
             "tasks": ["Irrigation quotidienne indispensable", "Traitement cochenilles agrumes"]},
        6:  {"plant": ["maïs tardif (irrigué)"],
             "harvest": ["blé (zones irriguées)", "oignons secs"],
             "tasks": ["Ombrage cultures sensibles", "Stocker eau pour été"]},
        7:  {"plant": [],
             "harvest": ["dattes (premières variétés)", "pastèques", "maïs"],
             "tasks": ["Irrigation bi-quotidienne palmiers", "Entretien système gravitaire"],
             "alert": "Vague de chaleur estivale — irriguer tôt le matin"},
        8:  {"plant": ["navets", "radis", "carottes"],
             "harvest": ["dattes", "figues", "raisins"],
             "tasks": ["Préparer sols pour automne", "Amender en compost"]},
        9:  {"plant": ["blé (précoce irrigué)", "fèves"],
             "harvest": ["dattes (pic récolte)", "olives (précoces)"],
             "tasks": ["Début récolte olives à l'huile", "Préparer pressoirs"]},
        10: {"plant": ["blé tendre", "orge", "oignons"],
             "harvest": ["olives", "dattes", "grenades"],
             "tasks": ["Semis irrigué céréales", "Récolte olives avant surmaturation"]},
        11: {"plant": ["fèves", "lentilles", "ail"],
             "harvest": ["olives", "oranges (début)", "grenades"],
             "tasks": ["Fertilisation oliviers (post-récolte)", "Taille légère oliviers"]},
        12: {"plant": ["pois", "épinards"],
             "harvest": ["olives (tardives)", "oranges", "choux"],
             "tasks": ["Irrigation réduite (dormance)", "Protection gel citrus"]},
    },

    "souss": {
        1:  {"plant": ["tomates (plein champ)", "poivrons", "haricots verts"],
             "harvest": ["clémentines", "oranges navel", "avocats"],
             "tasks": ["Récolte agrumes export", "Surveiller thrips sur poivrons"]},
        2:  {"plant": ["melons (sous tunnel)", "courgettes", "concombres"],
             "harvest": ["tomates (primeur)", "poivrons", "clémentines"],
             "tasks": ["Traitement acariens tomates", "Fertilisation agrumes"],
             "alert": "Pic de saison export — qualité sanitaire stricte requise"},
        3:  {"plant": ["pastèques (précoces)", "maïs doux"],
             "harvest": ["avocats", "oranges", "tomates sous tunnel"],
             "tasks": ["Irrigation goutte-à-goutte ajustée", "Désherbage sous tunnel"]},
        4:  {"plant": ["sorgho", "maïs (irrigué)"],
             "harvest": ["pastèques", "melons", "pommes de terre"],
             "tasks": ["Ébourgeonnage tomates", "Contrôle Tuta absoluta"]},
        5:  {"plant": ["haricots verts (2ème cycle)", "okra"],
             "harvest": ["maïs doux", "courgettes", "tomates"],
             "tasks": ["Irrigation accrue (chaleur)", "Surveillance acariens"],
             "alert": "Sécheresse estivale — vérifier débit goutte-à-goutte"},
        6:  {"plant": [],
             "harvest": ["oignons secs", "ail", "pastèques"],
             "tasks": ["Stockage agrumes en frigo", "Entretien filets ombrage"]},
        7:  {"plant": ["tomates (2ème cycle sous tunnel)"],
             "harvest": ["dattes", "figues"],
             "tasks": ["Préparer tunnels pour saison d'automne", "Fumigation sols"],
             "alert": "Chaleur extrême — suspendre travaux entre 11h et 16h"},
        8:  {"plant": ["tomates (plantation tunnel)", "poivrons", "aubergines"],
             "harvest": ["dattes", "figues", "argan (début)"],
             "tasks": ["Installation goutte-à-goutte nouveaux tunnels", "Paillis réflecteur"]},
        9:  {"plant": ["haricots verts export", "concombres", "courgettes"],
             "harvest": ["argan", "dattes", "raisins"],
             "tasks": ["Début grande saison maraîchère", "Calibrage pompes irrigation"]},
        10: {"plant": ["tomates (plein champ)", "poivrons (transplant)", "melons"],
             "harvest": ["citrons", "pamplemousses", "haricots verts"],
             "tasks": ["Fertilisation fond tunnel", "Nettoyage résidus cultures"]},
        11: {"plant": ["blé (zones irrigables)", "fèves", "pois"],
             "harvest": ["clémentines", "oranges (début)", "avocat"],
             "tasks": ["Taille agrumes après récolte", "Traitement fongique collet"]},
        12: {"plant": ["oignons", "carottes", "navets"],
             "harvest": ["oranges navel", "clémentines", "tomates tunnel"],
             "tasks": ["Récolte agrumes export intensif", "Surveiller gel nocturne"]},
    },

    "nord": {
        1:  {"plant": ["fèves", "pois", "oignons (bulbes)"],
             "harvest": ["choux", "brocolis", "poireaux"],
             "tasks": ["Surveiller mildiou sur légumes feuilles", "Drainage parcelles en pente"],
             "alert": "Risque pluies intenses et gel en altitude — protéger jeunes plants"},
        2:  {"plant": ["pommes de terre (précoces)", "petits pois", "laitues"],
             "harvest": ["carottes", "choux-fleurs", "épinards"],
             "tasks": ["Apport de chaux si sol acide", "Tailler kiwis et vignes"]},
        3:  {"plant": ["tomates (sous-abri)", "poivrons", "concombres"],
             "harvest": ["fèves vertes", "pois", "asperges"],
             "tasks": ["Préparer parcelles maraîchères", "Traitements cupriques vigne"]},
        4:  {"plant": ["maïs", "haricots verts", "courgettes", "melons"],
             "harvest": ["pommes de terre primeur", "fraises", "laitues"],
             "tasks": ["Traitements préventifs mildiou pommes de terre", "Tuteurer tomates"]},
        5:  {"plant": ["tournesol", "soja", "pastèques"],
             "harvest": ["petits pois", "fèves", "cerises", "fraises"],
             "tasks": ["Irrigation si déficit pluviométrique", "Éclaircissage fruits"]},
        6:  {"plant": ["maïs tardif", "haricots"],
             "harvest": ["blé", "orge", "cerises", "abricots"],
             "tasks": ["Moisson céréales (déb. juin)", "Traitement contre tordeuse"]},
        7:  {"plant": ["navets", "carottes d'automne", "fenouil"],
             "harvest": ["blé dur", "figues (premières)", "prunes"],
             "tasks": ["Labour post-récolte", "Entretien terrasses agricoles"]},
        8:  {"plant": ["brocolis", "choux de Bruxelles", "laitues"],
             "harvest": ["figues", "raisins", "poires"],
             "tasks": ["Préparer semis automne", "Taille en vert vigne"]},
        9:  {"plant": ["blé tendre", "orge", "pommes de terre (automne)"],
             "harvest": ["raisins", "figues", "noix"],
             "tasks": ["Vendanges", "Séchage figues"],
             "alert": "Premières pluies d'automne — fenêtre idéale pour semis céréales"},
        10: {"plant": ["blé", "orge", "fèves", "lentilles"],
             "harvest": ["pommes", "noix", "olives (début)"],
             "tasks": ["Semis céréales d'automne", "Récolte olives avant gel"]},
        11: {"plant": ["ail", "oignons", "pois"],
             "harvest": ["olives", "pommes tardives", "kiwis"],
             "tasks": ["Taille oliviers", "Enfouissement compost"]},
        12: {"plant": ["épinards", "mâche"],
             "harvest": ["olives (tardives)", "choux", "poireaux"],
             "tasks": ["Protection cultures contre gel et neige en altitude", "Entretien drains"]},
    },

    "oriental": {
        1:  {"plant": ["fèves", "pois chiches", "blé (tardif)"],
             "harvest": ["carottes", "navets", "choux"],
             "tasks": ["Irriguer si sol sec après semis", "Surveiller gel nocturne"],
             "alert": "Hivers rigoureux en altitude — éviter semis en plein gel"},
        2:  {"plant": ["oignons", "ail", "lentilles"],
             "harvest": ["épinards", "choux-fleurs"],
             "tasks": ["Amendement calcique si sol acide", "Désherbage préventif"]},
        3:  {"plant": ["pommes de terre", "tomates (abri)", "maïs (précoce)"],
             "harvest": ["fèves vertes", "pois"],
             "tasks": ["Préparer sol argilo-calcaire (labour)", "Traiter mildiou pommes de terre"]},
        4:  {"plant": ["maïs irrigué", "tournesol", "courgettes", "melons"],
             "harvest": ["pommes de terre primeur", "fèves sèches"],
             "tasks": ["Mise en eau canaux traditionnels (séguias)", "Tuteurer tomates"]},
        5:  {"plant": ["sorgho fourrager", "haricots verts"],
             "harvest": ["pois chiches", "ail", "laitues"],
             "tasks": ["Irrigation séguia céréales", "Surveillance pucerons"]},
        6:  {"plant": ["maïs tardif", "melons tardifs"],
             "harvest": ["blé", "orge", "oignons secs"],
             "tasks": ["Moisson manuelle/mécanisée", "Séchage grains avant stockage"],
             "alert": "Canicule — moissonner tôt le matin pour limiter les pertes"},
        7:  {"plant": [],
             "harvest": ["blé dur (tardif)", "tournesol", "pastèques"],
             "tasks": ["Labour profond après moisson", "Traiter greniers anti-charançons"]},
        8:  {"plant": ["navets", "carottes", "épinards"],
             "harvest": ["maïs grain", "sorgho", "melons"],
             "tasks": ["Préparer lit de semences automne", "Engrais vert (trèfle, vesce)"]},
        9:  {"plant": ["blé tendre", "orge", "fèves", "luzerne"],
             "harvest": ["maïs tardif", "sorgho", "raisins"],
             "tasks": ["Semis d'automne dans l'humidité résiduelle", "Vendanges"]},
        10: {"plant": ["blé dur", "pois chiches", "lentilles"],
             "harvest": ["olives", "grenades", "figues sèches"],
             "tasks": ["Labour et semis céréales", "Récolte grenades"],
             "alert": "Premières pluies automnales — opportunité semis sans irrigation"},
        11: {"plant": ["ail", "oignons", "féveroles"],
             "harvest": ["olives", "carottes"],
             "tasks": ["Fertilisation de fond", "Entretien séguias"]},
        12: {"plant": ["épinards", "blé tardif"],
             "harvest": ["olives (tardives)", "choux"],
             "tasks": ["Protection cultures contre gel continental", "Stockage fourrage"]},
    },
}

DEFAULT_REGION = "sais"

MONTH_NAMES_FR = [
    "", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
    "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"
]
MONTH_NAMES_AR = [
    "", "يناير", "فبراير", "مارس", "أبريل", "ماي", "يونيو",
    "يوليوز", "غشت", "شتنبر", "أكتوبر", "نونبر", "دجنبر"
]


def get_region(city: str) -> str:
    key = city.lower().strip()
    if key in CITY_REGION:
        return CITY_REGION[key]
    for k, r in CITY_REGION.items():
        if key in k or k in key:
            return r
    return DEFAULT_REGION


def get_calendar(city: str, month: int | None = None) -> dict:
    if month is None:
        month = date.today().month
    region = get_region(city)
    data = CALENDAR.get(region, CALENDAR[DEFAULT_REGION]).get(month, {})
    return {
        "region": region,
        "region_label_fr": REGION_LABELS[region]["fr"],
        "region_label_ar": REGION_LABELS[region]["ar"],
        "month": month,
        "month_name_fr": MONTH_NAMES_FR[month],
        "month_name_ar": MONTH_NAMES_AR[month],
        "plant": data.get("plant", []),
        "harvest": data.get("harvest", []),
        "tasks": data.get("tasks", []),
        "alert": data.get("alert"),
    }
